### ISSUE TITLE
Severe performance issue (adds 1.8 s to Neovim startup)

### ISSUE THREAD

**Issue by perguto** [mogelbrod/vim-jsonpath#15]
Just wanted to let you no that, while the plugin works, it adds 1.8 seconds to my Neovim startup time, which is definitively suboptimal.

From `nvim --startuptime`:
```
2203.899  1794.035  007.926: sourcing %HOME%\AppData\Local\nvim-data\plugged\vim-jsonpath\plugin\jsonpath.vim
```

**Comment by mogelbrod** [comment]
Not sure what could be the cause as the referenced vim file barely contains anything: https://github.com/mogelbrod/vim-jsonpath/blob/master/plugin/jsonpath.vim
Does the 1.8s second startup time go away if you disable the plugin?

**Comment by mogelbrod** [comment]
Closing since this plugin is unlikely to be the cause. Please provide a minimal repro otherwise!
